# Generated by Django 4.2.7 on 2023-11-05 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='', verbose_name='Файл обработанного видео')),
                ('threat_degree', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Степень угрозы')),
                ('ai_verdict', models.CharField(choices=[('Безопасно', 'безопасно'), ('Подозрительно', 'подозрительно'), ('Опасно', 'опасно')], default='Безопасно', max_length=25, verbose_name='Вердикт искуственного интелекта.')),
                ('most_dangerous', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Самый опасный момент')),
            ],
            options={
                'verbose_name': 'Обработанное видео',
                'verbose_name_plural': 'Обработанное видео',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='', verbose_name='Файл видео')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
    ]
