# Generated by Django 4.2.7 on 2023-11-09 11:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import source.services


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=source.services.get_path_to_upload, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('mp4',))], verbose_name='Файл видео')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='ProcessedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=source.services.get_path_to_upload, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('mp4',))], verbose_name='Файл обработанного видео')),
                ('threat_degree', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Степень угрозы')),
                ('ai_verdict', models.CharField(choices=[('Безопасно', 'безопасно'), ('Подозрительно', 'подозрительно'), ('Опасно', 'опасно')], default='Безопасно', max_length=25, verbose_name='Вердикт искуственного интелекта.')),
                ('most_dangerous', models.ImageField(blank=True, null=True, upload_to=source.services.get_path_to_upload, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png'))], verbose_name='Самый опасный момент')),
                ('source_video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processed_video', to='supersite.video', verbose_name='Исходное видео')),
            ],
            options={
                'verbose_name': 'Обработанное видео',
                'verbose_name_plural': 'Обработанное видео',
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_url', models.CharField(max_length=255, verbose_name='rtsp ссылка')),
                ('username', models.CharField(max_length=55, verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=55, verbose_name='Пароль')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
