# Generated by Django 4.2.7 on 2023-11-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supersite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, default='Без названия', max_length=255, verbose_name='Название'),
        ),
    ]
