# Generated by Django 4.2.7 on 2023-11-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supersite', '0002_alter_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, default='Без названия', max_length=255, null=True, verbose_name='Название'),
        ),
    ]
